services:
  gigglebook:
    image: ${DOCKER_REGISTRY-}gigglebook
    build:
      context: .
      dockerfile: GiggleBook/Dockerfile
    container_name: GiggleBook
    environment:
      DB_HOST: "master"
    ports:
      - 5090:8080
    depends_on:
      - "master"
    networks:
      - hw03

  master:
    image: postgres:15
    restart: unless-stopped
    container_name: master
    build: 
      context: .
      dockerfile: ./DbCluster/Master
    ports:
      - 5437:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: 
      -c config_file=/etc/postgresql.conf
      -c hba_file=/etc/pg_hba.conf
    volumes:
      - ./DbCluster/Volumes/master:/var/lib/postgresql/data
      - ./DbCluster/Volumes/replica_backup:/mnt/replica_backup
      - ./DbCluster/Volumes/master_postgresql.conf:/etc/postgresql.conf
      - ./DbCluster/Volumes/master_pg_hba.conf:/etc/pg_hba.conf
      # - ./GiggleBook/Initialize:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U replicator"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - hw03

networks:
  hw03:
    ipam:
      driver: default
      config:
        - subnet: 172.32.0.0/16