version: '3.4'

services:
  gigglebook:
    image: ${DOCKER_REGISTRY-}gigglebook
    build:
      context: .
      dockerfile: GiggleBook/Dockerfile
    environment:
      DB_HOST: "postgres_image"
    ports:
      - 5090:8080
    depends_on:
      - "postgres_image"
    networks:
      - default

  postgres_image:
    image: postgres:15
    restart: always
    ports:
      - 5437:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./GiggleBook/Initialize:/docker-entrypoint-initdb.d
    networks:
      - default

networks:
  default:
    driver: bridge 